import "./globals.css";
import Topo from './componentes/header/page.jsx'
import Footer from "./componentes/footer/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
      <Topo/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
